### ISSUE TITLE
Usuari empresa - Creació de qüestionaris - Resultats - Propostes de millora de fase

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#10]
No s'estan carregant les propostes de milora de les estratègies 'Ús', 'Reparació' i 'Reús'

![captura de pantalla 2018-09-02 a las 20 14 12](https://user-images.githubusercontent.com/42779858/44959419-2752fe00-aeee-11e8-91ce-6a36d5cccf6e.png)

**Comment by iboadella** [comment]
No, perque tenen una punctuacio de 1 (millor impossible) no crec que sigui millorable

**Comment by andriusmp** [comment]
Ah, entenc. Mostreu-les igualment les propostes de fase. Tot i que ho estiguin fent super bé. Aquestes propostes, fixes.

**Comment by iboadella** [comment]
ok,canviat

**Comment by andriusmp** [comment]
ok, comprovat
