### ISSUE TITLE
Usuari empresa - Duplicar qüestionaris

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#11]
L'opció de duplicar qüestionaris no fa res

**Comment by iboadella** [comment]
No et ensenya el error, pero no et deixa duplicar un quistionar enviat ( es correcte u ho hauria de deixar?)

**Comment by andriusmp** [comment]
No, ha de poder copiar qualsevol tipus de qüestionari. De fet, té més sentit amb els enviats que amb els altres. La idea és que jo, com a empresa, si no he canviat res, duplicaré el qüestionari que vaig enviar l'any anterior. Així que sempre actiu.

**Comment by iboadella** [comment]
OK, arreglat. ho he provat ara en pythonanwyhwere i em funciona

**Comment by andriusmp** [comment]
Perfecte, comprovat!!
