### ISSUE TITLE
Usuari empresa - Visualització d'un qüestionari puntuat

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#12]
Ara mateix l'usuari no té possibilitat de veure quines respostes ha donat per un qüestionari puntuat, perquè quan fa clic nomes pot veure els resultats. A l'especificació, es mostrava així:

![captura de pantalla 2018-09-02 a las 20 27 33](https://user-images.githubusercontent.com/42779858/44959469-caa41300-aeee-11e8-9527-5e98ee3e14d1.png)

Com a usuari, quan faig clic a sobre d'un qüestionari puntuat, no només m'hauria d'ensenyar els resultats del càlcul, si no un llistat de les respostes que he donat per cada pregunta.

**Comment by iboadella** [comment]
OK, fet, al final ara es veuen las preguntes i la repostes. si no et funciona a la primera, fes un refresh de la pagina

**Comment by andriusmp** [comment]
Ok, sí, ara es veuen les respostes!
Cal revisar l'export, perquè el PDF no té cap marge i talla les preguntes.

**Comment by andriusmp** [comment]
Ok.
Crec recordar que em vas dir que els marges del PDF etc. ho solucionaries amb el disseny. Tanco aquest issue.
