### ISSUE TITLE
Usuari admin - Creació d'usuaris

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#14]
Quan es crea un nou usuari des de l'usuari admin:

- A la pantalla de Datos Empresa, l'adreça que surt a dalt és la de l'administrador, no la de l'usuari que estem creant
- **El botó 'Registrar' no funciona. No sé si hi ha algun error de dades que no m'està mostrant.**
![captura de pantalla 2018-09-02 a las 20 57 57](https://user-images.githubusercontent.com/42779858/44959708-faedb080-aef2-11e8-970e-94598eb47620.png)
- Igualment, s'ha creat l'usuari, tot i que he hagut de cancelar per sortir de la pantalla. Els usuaris no s'han de crear fins que no estigui la segona part completa.
- Caldria afegir un botó cancelar que et torni a la llista d'usuaris (el mateix s'ha de fer a 'Editar usuari')

**Comment by iboadella** [comment]
Ara et funcionara. S havia colat una lletra en el codi

**Comment by andriusmp** [comment]
Cert, ja funciona el botó de registrar. Falta:
- Que a dalt surti el nom de l'usuari que s'està registrant, no de l'admin
- Els usuaris s'estan creant abans d'omplir la pantalla 'Dades d'empresa'. Això s'ha de canviar --> Ha d'arribar fins al final del procés!!!
- Ara que me n'adono, l'usuari que he creat és admin. Els usuaris admin no han de tenir Dades d'empresa associades. Per aquests usuaris, només la primera pantalla.
- Botó cancelar que et torni a la llista d'usuaris

**Comment by andriusmp** [comment]
Segueix passant això:

- Els usuaris s'estan creant abans d'omplir la pantalla 'Dades d'empresa'. Això s'ha de canviar --> Ha d'arribar fins al final del procés!!!

- Botó cancelar no et  torna a la llista d'usuaris

**Comment by andriusmp** [comment]
ok
