### ISSUE TITLE
Usuari admin - Descàrrega de tots els fitxers

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#15]
El botó que descarrega tots els fitxers dels qüestionaris que es mostren al llistat:
- Cal revisar-lo, perquè crec que no ho està descarregant tot
- Fa una doble primera carpeta
![captura de pantalla 2018-09-02 a las 21 19 30](https://user-images.githubusercontent.com/42779858/44959849-e363f700-aef5-11e8-9ad7-ac7afc003403.png)
- Els noms de les carpetes haurien de tenir sentit: nom de l'empresa_nom del qüestionari

**Comment by iboadella** [comment]
Si, crec que hi son tots. de totes maneres he canvait i ara surt en nom de la empresa, questionari i id de la pregunta

**Comment by andriusmp** [comment]
Comprovat!
