### ISSUE TITLE
Usuari empresa - Registre - Sectors

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#16]
1. El dropdown de sectors inclou una opció 'Sector' seleccionable.
2. No t'hauria de permetre continuar sense seleccionar el subsector (ara es pot fer sense problemes).
3. Igual amb el sector. Una empresa no es pot donar d'alta ni editar la seva informació deixant el sector i el subsector buits. Són camps **obligatoris**

**Comment by iboadella** [comment]
1- treta
2-implementat
3- fet

**Comment by andriusmp** [comment]
ok, comprovat
