### ISSUE TITLE
Usuari empresa - Qüestionaris - Informació/Ajuda

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#17]
La finestra d'ajuda (i) i la de informació sobre la pregunta (?) surten quan passes per sobre amb el cursor. Això és molt incòmode, ha de sortir només si l'usuari fa clic.

**Comment by iboadella** [comment]
canviat

**Comment by andriusmp** [comment]
No, segueix igual.

**Comment by andriusmp** [comment]
Funciona pels qüestionaris.
NO FUNCIONA pel (?) dels sectors quan s'estan modificant dades d'usuari.

**Comment by andriusmp** [comment]
ok
