### ISSUE TITLE
Usuari empresa - Esborrar qüestionaris

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#18]
- Seleccionar un qüestionari enviat
- Esborrar

Surt la finestra de doble confirmació i cap avís de que no es pot esborrar per estar puntuat (això sí, no s'esborra).
En comptes de la doble confirmació, en aquest cas ha de sortir una finestra que digui que no pot esborrar-lo (o que es desactivi el botó d'esborrar quan un qüestionari puntuat es seleccioni).

**Comment by iboadella** [comment]
ok,surt doble confirmacio i despres expliquem perque no pot. Seria millor canviar el ordre pero tal com esta fet, seria forca feina

**Comment by andriusmp** [comment]
Ok, ho deixem així
