### ISSUE TITLE
Usuari empresa - Llistat de qüestionaris

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#19]
- Revisar el títol de la puntuació obtinguda (surt 'obtinguda' dos cops)
![image](https://user-images.githubusercontent.com/42779858/44975652-417af380-af63-11e8-8b87-b3839f000709.png)
- ¿Podríem afegir aquí la mateixa llegenda que hi ha al llistat de qüestionaris de l'usuari admin? Per a que entengui què volen dir els colors exactament.

**Comment by iboadella** [comment]
ok,fet

**Comment by andriusmp** [comment]
ok
