### ISSUE TITLE
Condicions legals

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#2]
1. Surt aquest missatge: 'Welcome to Your Vue.js App' i no surt el text associat (el mateix des de l'enllaç del registre d'usuari
2. No es pot tornar enrera! Un cop entres a condicions legals només pots moure't pel menú de dalt, no pots tornar a la Home

**Comment by iboadella** [comment]
1. No tenim el text de condicions legals
2. si fas click al icone encercla t'haurie de redirigir a la pagina inicial

**Comment by andriusmp** [comment]
1. Cert, tens raó
2. Això només funciona quan l'usuari està loggejat. Des de la pantalla d'inici el botó 'Encercla' no fa res

**Comment by andriusmp** [comment]
2. Segueix exactament igual:
- Sense fer login, clic a 'Condicions legals'
- Surt el botó de logout (això no té cap sentit, encara no m'he loggejat)
- Fins que no toco logout, faig clic a la Home i no fa cas

**Comment by andriusmp** [comment]
ok
