### ISSUE TITLE
Usuari admin - Gestió de qüestionaris - Filtres

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#21]
El contingut del filtre 'Estat' no està traduit
![image](https://user-images.githubusercontent.com/42779858/44979659-f87c6c80-af6d-11e8-963a-f5b12c69383e.png)

Igual amb altres filtres:
![image](https://user-images.githubusercontent.com/42779858/44981400-b86bb880-af72-11e8-861e-665a9f1708e7.png)

**Comment by iboadella** [comment]
ok,arreglat

**Comment by andriusmp** [comment]
ok, comprovat
