### ISSUE TITLE
Usuari admin - Gestió de qüestionaris - Edició

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#22]
Si fem clic (usuari admin) a un qüestionari pendent: permet editar el qüestionari --> OK!
Si fem clic (usuari admin) a un qüestionari enviat: permet editar el qüestionari --> NO!! Un qüestionari enviat és un registre, no s'ha de poder canviar. Hauria de portar-te al resum de respostes, resultat i gràfic, igual que el que veu l'usuari empresa

**Comment by iboadella** [comment]
ok,canviat

**Comment by andriusmp** [comment]
ok
