### ISSUE TITLE
General - ES/CAT - Missatges d'error

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#23]
Els missatges d'error estan embedded al codi, tots escrits en català.
S'ha d'adaptar al sistema bilingüe.

**Comment by iboadella** [comment]
En principi no, pero segur que ens ha escapar en mes de un cop. em pots donar un parell d'exemples ,si us plau

**Comment by andriusmp** [comment]
No recordo per quin missatge ho vaig posar. Tanco, si ho tornés a trobar obro un altre issue.
