### ISSUE TITLE
Usuari administrador - Gestió de qüestionaris - Descarregar arxius adjunts de tots els qüestionaris

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#24]
1. **No funciona a la primera**. Li he de fer un número variable de clics abans que reaccioni (de vegades 2, de vegades 5, ha arribat a ser 26)
![image](https://user-images.githubusercontent.com/42779858/44980947-86a62200-af71-11e8-9a35-39bc886fa33b.png)

2. Quan els filtres estan activats, els arxius que es descarreguin amb aquest botó han de coincidir amb els qüestionaris que es mostren per pantalla, no amb tots.
![image](https://user-images.githubusercontent.com/42779858/44981027-b8b78400-af71-11e8-9aba-3541c41a1928.png)

3. Podem canviar el nom de l'arxiu zip que es descarrega?
Posem per exemple data i hora de la descàrrega: 20180903_1158

**4. No s'està descarregant el DARI pels qüestionaris que el tenen adjunt**

**Comment by dpiscia** [comment]
1- ens ha funcionat a la primera, despres ho tornem a provar
2- fet
3- hem estat mirant-ho i no es facil
4 fet

**Comment by andriusmp** [comment]
Doncs a mí ara ha arribat el punt que NO em funciona. Cap vegada.
Error que surt:
![image](https://user-images.githubusercontent.com/42779858/45170671-b6b72480-b200-11e8-8f38-593014654ab5.png)

**Comment by andriusmp** [comment]
Sí, ara es descarrega, però li posa format Excel amb el que òbviament no es pot obrir

**Comment by andriusmp** [comment]
ok
