### ISSUE TITLE
Usuari administrador - Gestió de qüestionaris - Descarregar arxius adjunts d'un qüestionari

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#25]
1. Canviem el nom del zip que es descarrega. En aquest cas: Data_Hora_Nomqüestionari
Exemple: 20180903_1208_EmpresaAndrea.v1-2018

2. Les carpetes haurien de tenir el número de pregunta. Ara tenen una numeració que no acabo d'entendre
![image](https://user-images.githubusercontent.com/42779858/44981190-2c599100-af72-11e8-8735-e3aafdb57fc6.png)

3. **No s'està descarregant el DARI pels qüestionaris pels que s'ha adjuntat**

**Comment by iboadella** [comment]
1- hem posat id de la pregunta
2- dari affegit

**Comment by andriusmp** [comment]
Sí, ara es descarrega, **però li posa format Excel amb el que òbviament no es pot obrir**
Per un altra banda, segueixo sense entendre el nom de les carpetes. A la prova que he fet m'ha sortit això:
![image](https://user-images.githubusercontent.com/42779858/45203706-43072d00-b27d-11e8-908f-1a4b4f17130b.png)
25 és el correponent a la 4º pregunta de l'usuari; 37 és el DARI (que no té pregunta associada, hauria de ser 0, per exemple). Si no hi ha manera de relacionar els arxius adjunts amb alguna cosa que sigui identificable per l'usuari (25 i 37¿?¿?), llavors no té cap sentit posar-hi carpetes.

**Comment by andriusmp** [comment]
Els números de les carpetes segueixen sense tenir sentit per l'usuari: no estan associades al número de pregunta real (suposo que és la codificació interna de les preguntes)

**Comment by andriusmp** [comment]
Vam dir de deixar-ho així, oi?
