### ISSUE TITLE
Usuari administrador - Gestió de qüestionaris - Descarregar excel amb respostes

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#26]
1. Nom de l'arxiu: Posem data i hora de descàrrega (20180903_1220.slsx) 
2. Ordre: posem la columna 'id' la primera. Després 'preguntes' i finalment les respostes.
3. Només s'han de descarregar les respostes dels qüestionaris enviats (les altres podrien variar)
4. Només s'han de descarregar les respostes dels qüestionaris llistats segons filtres
5. Idioma: s'ha de descarregar en l'idioma que estigui configurat en aquell moment

**Comment by iboadella** [comment]
1-fet
2-fet
3-complicat, no entenc perque podrien variar
4-fet
5- fet

**Comment by andriusmp** [comment]
1- ok, comprovat
2- id està la primera, però ara la columna de preguntes està por ahí perdida
![image](https://user-images.githubusercontent.com/42779858/45167541-a2235e00-b1f9-11e8-8723-98117586a0df.png)
3- home... doncs perquè si no estan enviats els qüestionaris, l'usuari encara els pot modificar. No es pot consultar la variable 'estat' i afegir només els 'enviats'???? A més, així pot haver-hi preguntes que li apliquin i no estiguin respostes. I perquè barrejar qüestionaris puntuats amb qüestionaris pendents amb 100 qüestionaris que pugui crear l'usuari de prova, no crec que tingui gaire valor d'anàlisi de dades...
4- ok, comprovat
5- ok, comprovat

**Comment by andriusmp** [comment]
L'he tancat sense voler, segueix obert.

**Comment by andriusmp** [comment]
ok
