### ISSUE TITLE
General - Interfície - Favicon

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#28]
El nom que es mostra a la pestanya del navegador s'ha de corregir. Ara posa encercle, ha de posar enCErcla
![image](https://user-images.githubusercontent.com/42779858/44981585-4c3d8480-af73-11e8-8e9d-0759f0b0143a.png)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
comprovat
