### ISSUE TITLE
Usuari empresa - Creació de qüestionaris - No funciona segons sector

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#29]
La creació de qüestionaris no funciona pels següents sectors:
- Comercial
- Serveis
- Públic
- Altres

Surt la finestra de 'Qüestionari nou', però el botó Crear no passa a la següent pantalla. Internament, sí que es crea el qüestionari.

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok, comprovat
