### ISSUE TITLE
Checkbox 'accepto les condicions'

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#3]
Si no el marques, no pots continuar, però no es mostra cap missatge (s'ha de donar avís a l'usuari de perquè no pot seguir)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok, però el text està malament en castellà i en català

- Català: Has **de acceptar** les condicions legals (incorrecte) --> És necessari acceptar les condicions legals
- Castellà: Tienes que **acceptar** las condiciones legales (incorrecte) --> Es necesario aceptar las condiciones legales

**Comment by iboadella** [comment]
ok. aquest text no ho tenia

**Comment by andriusmp** [comment]
Ok
