### ISSUE TITLE
Usuari empresa - Visualització qüestionaris - Colors segons puntuació

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#30]
Un qüestionari amb puntuació '0' mostra la boleta en verd. Hauria de ser vermell.
![image](https://user-images.githubusercontent.com/42779858/44983226-ccb2b400-af78-11e8-8251-66df3e31cb96.png)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok, comprovat
