### ISSUE TITLE
Usuari empresa - Creació de qüestionaris - Informació de les preguntes

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#31]
1. S'ha de millorar el HTML. El que són preguntes han d'estar amb un salt de línia final, amb negreta, etc. Ara està tot junt, preguntes, respostes,... I no s'enten.
2. Algunes imatges es surten de la subfinestra. Aquesta finestra s'hauria d'adaptar a la taula
![image](https://user-images.githubusercontent.com/42779858/44983613-1059ed80-af7a-11e8-84c2-4714badbd4ec.png)
3. Aquestes imatges s'han d'adaptar segons l'idioma. Tenen text incrustat, pel que s'ha d'agafar la imatge que toqui.

**Comment by iboadella** [comment]
2 fet

**Comment by andriusmp** [comment]
accents, codi pel mig del text

![image](https://user-images.githubusercontent.com/42779858/45204703-59fb4e80-b280-11e8-8cb8-278df2e6af41.png)

**Comment by andriusmp** [comment]
![image](https://user-images.githubusercontent.com/42779858/45204721-68e20100-b280-11e8-899a-00066da9d113.png)

**Comment by andriusmp** [comment]
![image](https://user-images.githubusercontent.com/42779858/45204789-9038ce00-b280-11e8-92f1-2f881a135324.png)

**Comment by andriusmp** [comment]
![image](https://user-images.githubusercontent.com/42779858/45204800-9af36300-b280-11e8-8596-9093d204c3d3.png)

**Comment by andriusmp** [comment]
Aquestes imatges segueixen sense sortir

**Comment by andriusmp** [comment]
Tanco aquest. Veure issue #50
