### ISSUE TITLE
General - Disseny gràfic

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#32]
Coses específiques a tenir en compte quan apliqueu el disseny:
1. Les taules tant d'usuaris com de qüestionaris s'ha de poder ordenar segons columna.
2. Algunes accions de la gestió d'usuaris, gestió de qüestionaris i visualització de qüestionaris hauria de poder aplicar-se a diverses files. Per exemple, per esborrar varis usuaris, l'administrador ha d'anar 1 a 1.
3. No surt enlloc l'avís de "Les dades introduïdes són confidencials i susceptibles de revisió per part del personal de la ADCC.". Això és independent de de les condicions, i s'ha de mostrar abans d'enregistrar-se.
![image](https://user-images.githubusercontent.com/42779858/44986886-79932e00-af85-11e8-8de3-2cd486d0c259.png)

**Comment by iboadella** [comment]
3-fet
1,2 : en parlem
