### ISSUE TITLE
Usuari empresa - Creació de qüestionaris - DARI

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#33]
Estaria bé explicar una mica més l'arxiu que es demana. Posem:
- Català: Adjuntar DARI (Declaració Anual de Residus Industrials) de l'any corresponent a l'exercici que s'està avaluant.
- Castellà: Adjuntar DARI (Declaración Anual de Residuos Industriales del año correspondiente al ejercicio que se está evaluando.

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok, però falta un parèntesi al castellà (sorry, jo no l'havia posat):
Adjuntar DARI (Declaración Anual de Residuos Industriales) del año correspondiente al ejercicio que se está evaluando.

**Comment by andriusmp** [comment]
Sobra un espai entre Industriales i el parèntesi...
