### ISSUE TITLE
PETICIÓ CLIENT: Usuari administrador - Gestió de qüestionaris - Filtres

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#36]
El client demana dos filtres més:
- Filtre per 'Territori Leader'
- Filtre per 'Any de convocatòria' (veure #38)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
Ok. Podem afegir filtre pel booleà 'Es presenta a Leader'?

**Comment by andriusmp** [comment]
ok
