### ISSUE TITLE
PETICIÓ CLIENT: concepte 'Any convocatòria'

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#38]
Cada qüestionari ha de tenir associats dos camps internament:
1) **Es presenta a convocatòria?** Valor booleà Sí/No --> Això és perquè volen abarcar la gent que fa el qüestionari sense intenció de presentar-lo 'oficialment'
2) **Any de convocatòria** --> Això és perquè pot ser que s'estigui omplint a gener un qüestionari destinat a les ajudes de l'any anterior, pel que hem de saber a quina convocatòria està associat cada qüestionari (les convocatòries van per any.

Aquesta informació s'hauria de demanar per cada qüestionari. Ho podem fer a la finestra de creació, just abans del botó 'Crear'
![image](https://user-images.githubusercontent.com/42779858/44992812-adc41a00-af98-11e8-8c53-53741e1b470a.png)
1) Checkbox marcat per defecte amb el text 'Qüestionari per presentar sol·licitud a una convocatòria d'ajuts Leader'.
2) Desplegable amb anys (iniciem amb 2017 i fins a l'any actual). Si l'usuari desactiva el checkbox 2, aquest combo es desactiva.

Aquests camps s'haurien de mostrar també a la taula del llistat de qüestionaris, són importants, i com a un filtre més a la gestió de qüestionaris de l'usuari administrador. #36

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
i) Funciona per empreses que tenen DARI.
ii) Per les altres (que també han de tenir el checkbox i el desplegable), surt la pantalla buida i no et deixa avançar perquè dona l'error 'Has de seleccionar un any'
![image](https://user-images.githubusercontent.com/42779858/45205894-e0655f80-b283-11e8-9a98-ce31d65d6102.png)

**Comment by andriusmp** [comment]
També falta aquesta part:
**Aquests camps s'haurien de mostrar també a la taula del llistat de qüestionaris, són importants, i com a un filtre més a la gestió de qüestionaris de l'usuari administrador.**
Perquè si l'usuari ho introdueix quan crea el qüestionari, però l'administrador mai pot veure-ho enlloc...

**Comment by andriusmp** [comment]
Ara surt bé el combo i el checkbox també per les que no tenen DARI, però em deixa crear sense marcar res.

**Comment by andriusmp** [comment]
Ok
