### ISSUE TITLE
Registre nova empresa

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#4]
1. Els missatges d'error estàn en castellà. Això s'ha de canviar segons l'idioma
2. Deixa crear l'usuari sense seleccionar la comarca ni el territori Leader

**Comment by iboadella** [comment]
1. aquests tipus de missatges  d'error de formulari son funcionalitats natives del html, i fan servir el idioma del teu ordenador. De fet ens surten en ingles a nosaltres. 
2. Resolt

**Comment by andriusmp** [comment]
1. ok
2. ok
