### ISSUE TITLE
Usuari empresa - Registre

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#40]
L'usuari es crea sense dades després de la primera pantalla. Crec que ho hem comentat força vegades, l'usuari no s'ha de crear fins al final. Seqüència de reproducció:
- Botó Registrar-se
- Omplir correu electrònic i contrasenya, acceptar les condicions i clic a 'Registrar'
- A la pantalla d'omplir la resta de dades, fer clic a enCErcla.
S'entra a l'usuari, que s'ha creat sense nom i sense cap dada interna.

**Comment by iboadella** [comment]
hi ha un issue obert (14) per aixo, i encara no l hem resolt. per aixo no te una etiqueta tobetested

**Comment by andriusmp** [comment]
ok, cert
