### ISSUE TITLE
Usuari administrador - Excel puntuacions

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#42]
Revisant l'excel amb les puntuacions dels qüestionaris:

1) La puntuació futurible no pot ser mai menor que l'altra, perquè és la puntuació obtinguda + x
![image](https://user-images.githubusercontent.com/42779858/45207207-adbd6600-b287-11e8-8f96-867f19694cad.png)

2) No entenc com s'està calculant la puntuació obtinguda.
Per exemple, en el cas del qüestionari gg.v1-2018. L'aplicació mostra 58,57. He fet el càlcul amb les puntuacions que surten al excel fent un promig a saco i surt 61,11. I fent-ho amb la fòrmula que et vaig posar, que fa càlculs per estratègies, surt 68.3. T'adjunto l'excel amb els meus càlculs.
[07092018_0911.xlsx](https://github.com/iboadella/encercla_client/files/2360213/07092018_0911.xlsx)

**Comment by iboadella** [comment]
Si divideix per 6, surt 68,3 ,si divideix per 7 surt 58.57, jo diria que son 7 sectors. em sembla que en el teu excel falta tenir en compte la resposta "modularitat del producte" (P22) que es del sector "Remafactura".

[07092018_0911_iris.xlsx](https://github.com/iboadella/encercla_client/files/2364129/07092018_0911_iris.xlsx)

**Comment by andriusmp** [comment]
Tens raó, error meu. La puntuació actual està bé.
Les futuribles no! Com a mínim han de ser iguals a les actuals. La puntuació futurible no pot ser mai menor que l'altra, perquè és la puntuació obtinguda + x

**Comment by andriusmp** [comment]
Tampoc surt la puntuació total.

**Comment by andriusmp** [comment]
Ok
