### ISSUE TITLE
Edició de dades d'usuari

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#5]
1. No s'enten que sigui una pàgina que et permeti canviar les dades, donat que es titula 'Change email' (si us plau, utilitzeu els textos del excel)
2. De fet, no comprova res aquest primer pas, es pot posar qualsevol password i tira igualment

No crec que en aquest pas sigui necessari un login, ja està loggejat a la seva sessió.

**Comment by iboadella** [comment]
1. fet
2. ara si comprova
No has de introduir la contrasenya, nomes ho fas si la vols canviar

**Comment by andriusmp** [comment]
1. ok
2. ok

Crec que aquest procés de modificació de dades no s'entén en absolut tal com està. Coses que crec que s'han de canviar per a intentar millorar-ho:
- El primer és posar les coses en l'idioma que toca. Ara mateix posa 'Password' i 'Change Password'.
- Després, el text hauria de ser 'Nova contrasenya' i 'Repetir nova contrasenya' / 'Nueva contraseña' y 'Repetir nueva contraseña'.
- Com a usuari, si jo no vull canviar la contrasenya i és el primer que em mostres i l'únic botó que hi ha és 'Actualitzar', és molt difícil que pugui interpretar que si no escric res podré continuar editant altres coses. Cal buscar un altra solució. 

El que podem fer és:
1. posar totes les modificacions a la mateixa pantalla: password i dades d'usuari.
2. afegir un botó de cancel·lar.

**Comment by andriusmp** [comment]
Ok. veig que ara són 2 processos diferents, em sembla bé.
Entenc que quan apliqueu el disseny s'entendrà millor on clicar per cada cosa.
Tanco.
