### ISSUE TITLE
Usuari empresa - Creació qüestionari - Checkbox convocatòria ajuts

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#51]
La frase "Qüestionari per presentar sol·licitud a una convocatòria d'ajuts Leader" surt duplicada
![image](https://user-images.githubusercontent.com/42779858/46604437-8f50c180-caf6-11e8-969d-51490b97839d.png)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok
