### ISSUE TITLE
Usuari empresa - Creació qüestionari - Nom assignat al qüestionari

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#53]
Cal revisar com s'assignen els noms als qüestionaris, perquè he aconseguit tenir 2 amb el mateix nom, i això no pot passar:

![image](https://user-images.githubusercontent.com/42779858/46605330-7564ae00-caf9-11e8-9abc-6b768fd7d916.png)
![image](https://user-images.githubusercontent.com/42779858/46605370-8b726e80-caf9-11e8-90d4-2797971f8d57.png)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok
