### ISSUE TITLE
Botons 'Cancel·lar'

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#55]
Cal revisar tots els botons de 'Cancel·lar' en català, perquè hi ha una falta d'ortografia (ara posa 'Cancelar')

**Comment by andriusmp** [comment]
Ara està amb un guionet (Cancel-lar). Això no és correcte, s'ha d'utilitzar el punt del 3 (Cancel·lar)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok
