### ISSUE TITLE
Usuari administrador - Evolució de l'empresa

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#59]
L'eix vertical no ha de canviar segons la puntuació de l'empresa. L'eix va del 0 al 100 sempre. Llavors s'ha de veure marcada la puntuació dels diferents anys on toca.  Seria algo així:

![image](https://user-images.githubusercontent.com/42779858/47372637-71847e80-d6ea-11e8-85f5-79f15e6f53ee.png)

**Comment by iboadella** [comment]
he fixat el y de 0 a 100. si tens dades sobre dos anys surt la linea, sino no es veu res.

**Comment by andriusmp** [comment]
Els títols dels eixos estan per dintre. Quan es marqui una puntuació, la del primer any pot mostrar-se a sobre del títol de l'eix 'puntuació'
