### ISSUE TITLE
Usuari administrador - Extracció d'informes - Precisió

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#60]
Les mitjanes, podem ajustar-les a només 2 decimals?

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
Al servidor Catcentral: **no surt res a la finestra d'extracció d'informes.**
![image](https://user-images.githubusercontent.com/42779858/47705621-5607ff00-dc27-11e8-8634-1fe55b127a25.png)

**Comment by andriusmp** [comment]
ok
