### ISSUE TITLE
URGENT / Producció / Usuari empresa - Creació de qüestionari - Error

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#63]
La creació de qüestionaris dona un error:
![image](https://user-images.githubusercontent.com/42779858/47654577-65396f00-db8b-11e8-8585-416e375dfd11.png)
Passa tant si s'ha d'adjuntar DARI com si no.

**Comment by iboadella** [comment]
problemes amb las dades pujada en el mysql. resolt

**Comment by andriusmp** [comment]
ok
