### ISSUE TITLE
URGENT / Producció / Usuari administrador - Login no funciona

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#64]
L'usuari administrador s'ha creat amb l'script, però no em puc loggejar.
Dona un INTERNAL SERVER ERROR:
![image](https://user-images.githubusercontent.com/42779858/47654818-f14b9680-db8b-11e8-86b9-b39bd4698415.png)
![image](https://user-images.githubusercontent.com/42779858/47655177-ba29b500-db8c-11e8-87f9-b282e611ba41.png)

**Comment by iboadella** [comment]
mateix que issue #65

**Comment by andriusmp** [comment]
ok
