### ISSUE TITLE
URGENT / Producció / Usuari administrador - Login - Contrasenya no encriptada

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#65]
La contrasenya del usuari administrador creat amb l'script no es guarda encriptat, pot ser el problema que genera l'issue #64 ?

![image](https://user-images.githubusercontent.com/42779858/47655020-65863a00-db8c-11e8-8d23-ef3de55f759c.png)

**Comment by iboadella** [comment]
ara hauria de funcionar, quan el admin executa python create_admin.py

**Comment by andriusmp** [comment]
ok
