### ISSUE TITLE
DISSENY - Logo inicial

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#69]
El logo de la pantalla d'inici no té la tipo correcta.

Actual:
![image](https://user-images.githubusercontent.com/42779858/48009989-f9bc4800-e11c-11e8-9189-8c1c52a56f33.png)
Hauria de ser:
![image](https://user-images.githubusercontent.com/42779858/48009999-00e35600-e11d-11e8-9485-c0724ba95b5b.png)

El logo sencer amb el text ja inclòs te'l vaig enviar, per a que no hagis de triar la tipo.

**Comment by iboadella** [comment]
El problema es que si faig servir el logo sencer no podre fer que els botons "inciar sessio"  siguin botton de veritat amb una accion acociada

**Comment by andriusmp** [comment]
ok
