### ISSUE TITLE
Inici de sessió

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#7]
No funciona. Faig clic a iniciar sessió i no fa cap paper.

**Comment by andriusmp** [comment]
L'usuari que no funciona és andrea@ineditinnova.com. Seqüència de reproducció:
1. He creat l'usuari amb la contrassenya 1234
2. He editat les dades d'usuari. Com que a aquesta edició posa "Change password", he escrit el password inicial (1234) al primer textbox i un nou password (admin) al segon.
3. He fet clic a Register (s'ha de canviar aquest títol!!!!!!!)
4. He continuat fent modiciacions de les dades de l'empresa

A partir d'aquí no m'ha deixat tornar a loggejar-me. Ni amb la contrasenya 1234 ni amb admin

**Comment by iboadella** [comment]
OK, reproduit i resolt (et he tornat a posar contraseña 'admin'). ho pots comprovar

**Comment by andriusmp** [comment]
Perfecte, comprovat!
