### ISSUE TITLE
BUG - Usuari empresa - Colors de gràfic resultant

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#76]
Els colors no s'estan calculant bé, surt sempre en verd (excepte etapes que no apliquen).
Exemple:
![image](https://user-images.githubusercontent.com/42779858/48013227-1f991b00-e124-11e8-8ff9-298c7aa7eb4e.png)
La puntuació és 0 i en canvi les estratègies que apliquen són verdes.

**Comment by andriusmp** [comment]
S'hauria de calcular amb aquests valors:
![image](https://user-images.githubusercontent.com/42779858/48013314-4fe0b980-e124-11e8-8486-9122b1a3bfc1.png)

**Comment by iboadella** [comment]
ok, hi havia un petit error en el color assignat

**Comment by andriusmp** [comment]
No, segueix calculant-se malament:
![image](https://user-images.githubusercontent.com/42779858/48791952-50b44680-ecf3-11e8-9b92-8588e116f5cd.png)

**Comment by iboadella** [comment]
canviat

**Comment by andriusmp** [comment]
ok
