### ISSUE TITLE
Usuari empresa - Creació de qüestionaris - Títols i barra de progrés 

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#8]
- Al títol d'un nou qüestionari s'afegeix la paraula 'Company'. Això no hauria d'estar
- Segueix sortint el text "Score". Ho podeu treure? Ha de quedar només el número de pregunta on estan.
- Si en algún moment ha sortit l'error 'You have to complete the futurible answer', s'afegeix al títol de les preguntes i es mostra tota la estona
![captura de pantalla 2018-09-02 a las 20 14 12](https://user-images.githubusercontent.com/42779858/44959344-11910900-aeed-11e8-8dbb-c6216b317ebb.png)

**Comment by iboadella** [comment]
fets

**Comment by andriusmp** [comment]
Les modificacions aquestes que feu són al servidor? Perquè jo ho veig igual... :(

**Comment by andriusmp** [comment]
Ok, lo de score ja no surt.
Però segueix afegint el missatge d'error al títol:
![captura de pantalla 2018-09-02 a las 22 51 40](https://user-images.githubusercontent.com/42779858/44960605-e0bbce80-af02-11e8-97da-58252e6cd57c.png)

**Comment by andriusmp** [comment]
Comprovat!

**Comment by andriusmp** [comment]
Quan l'admin modifica les preguntes que apliquen a un usuari, la barra de progrés dels qüestionaris que estaven creats prèviament no ho té en compte:

![image](https://user-images.githubusercontent.com/42779858/44983783-c291b500-af7a-11e8-9197-e0babc203662.png)

Com que internament continua tenint 12 preguntes però l'usuari només en pot resoldre 2, NO DEIXA ENVIAR EL QÜESTIONARI PER PUNTUAR

**Comment by andriusmp** [comment]
Quan l'admin modifica les preguntes que apliquen a un usuari, la barra de progrés dels qüestionaris que estaven creats prèviament no ho té en compte:

![image](https://user-images.githubusercontent.com/42779858/44983783-c291b500-af7a-11e8-9197-e0babc203662.png)

Com que internament continua tenint 12 preguntes però l'usuari només en pot resoldre 2, NO DEIXA ENVIAR EL QÜESTIONARI PER PUNTUAR

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
Doncs no
![image](https://user-images.githubusercontent.com/42779858/45169672-66d75e00-b1fe-11e8-9266-97f0711812b5.png)

**Comment by andriusmp** [comment]
Ok
