### ISSUE TITLE
Usuari empresa - No es mostra la puntuació futurible correcta

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#82]
El resultat un cop enviat el qüestionari a puntuar no mostra la puntuació futurible adequada:
![image](https://user-images.githubusercontent.com/42779858/48266750-a6a20800-e430-11e8-9baa-9a508ac7775a.png)

![image](https://user-images.githubusercontent.com/42779858/48266761-b3bef700-e430-11e8-936e-247e66e57a50.png)

**Comment by iboadella** [comment]
OK, canviat.

**Comment by andriusmp** [comment]
No funciona. Ara, pel mateix cas que et posava mostra:
![image](https://user-images.githubusercontent.com/42779858/48790684-37f66180-ecf0-11e8-9341-54282dcbb193.png)
I a la taula de la Home posa 73 (de fet no té sentit una puntuació futurible menor que la obtinguda, imagino que falta sumar-la)

**Comment by iboadella** [comment]
corregit

**Comment by andriusmp** [comment]
ok
