### ISSUE TITLE
Usuari empresa - Com sé a quin any he presentat un qüestionari?

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#84]
Com a usuari empresa jo veig una llista de qüestionaris, però no tinc cap forma de veure a quina convocatòria l'he presentat i, de fet, si l'he presentat a convocatòria. Aquesta informació es perd per l'usuari en el moment en que dona ok a crear. Aquestes dues informaciones haurien de ser dos columnes més a la visualització de qüestionaris (tant per usuari empresa com per usuari administrador), i hauria de ser un camp més a:

![image](https://user-images.githubusercontent.com/42779858/48267564-f7b2fb80-e432-11e8-8077-7217521de4a8.png)

**Comment by iboadella** [comment]
fet

**Comment by andriusmp** [comment]
ok
