### ISSUE TITLE
Usuari administrador - Veure evolució

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#85]
No m'està mostrant cap evolució d'una empresa que té un test del 2017 i l'altre del 2018.

![image](https://user-images.githubusercontent.com/42779858/48268192-a3108000-e434-11e8-9be4-c111b1a9cb74.png)

Pot ser que per algun motiu no estigui reconeixent el qüestionari de 2017?

**Comment by iboadella** [comment]
el any no pot set el 2017 perque es el any en el que es ha publicat el questionari, el 2017 entence que es l any de convocatoria (no de publicacio)

**Comment by andriusmp** [comment]
No. Per veure l'evolució de l'empresa, el que compta és l'any de convocatòria, no el de creació del qüestionari. Si s'està presentant a la convocatòria de 2017 vol dir que les respostes que donen són de la situació de l'empresa en aquell any.

**Comment by iboadella** [comment]
tret

**Comment by andriusmp** [comment]
ok
