### ISSUE TITLE
Usuari empresa - Duplicar qüestionaris

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#86]
No permet duplicar qüestionaris!!!! Em dona el missatge com si l'usuari no tingués aquest permís, però sí que el té!
A més, el missatge de 'No es pot duplicar el qüestionari' es queda a les finestres (quan vull crear un qüestionari nou, surt a sota de l'any de convocatòria):
![image](https://user-images.githubusercontent.com/42779858/49008941-761bd700-f16f-11e8-8263-310998b93d27.png)

**Comment by iboadella** [comment]
fet
