### ISSUE TITLE
Usuari empresa - Creació de qüestionaris - Informació

### ISSUE THREAD

**Issue by andriusmp** [iboadella/encercla_client#9]
El botó de 'i' mentre s'està creant un qüestionari no funciona

**Comment by iboadella** [comment]
ho acabem de provar i ens funciona. Ho pots tornar a provar?

**Comment by andriusmp** [comment]
No... El botó de (?) sí que funciona (tot i que surt sense que faci clic, només passant per sobre, això s'hauria de canviar), però el de (i) res. Surt la pantalla d'instruccions quan creo el formulari, això sí, però mentre estic responent, no funciona.

**Comment by andriusmp** [comment]
Comprovat! Funciona
